### ISSUE TITLE
Support parameters with properties

### ISSUE THREAD

**Issue by tineheller** [otris/jsdoc-tsd#13]
**Parameters with properties** are described in
http://usejsdoc.org/tags-param.html#parameters-with-properties

The **paramters with properties** are required to generate `d.ts` files for additional DOCUMENTS modules like **DocumentsContext**.

At the moment all parameter properties are added to the parameters in the function declaration.

**Comment by wehrstedt** [comment]
TODO: Add a test for this type of annotation:
``´
/**
 * Assign the project to a list of employees.
 * @param {Object[]} employees - The employees who are responsible for the project.
 * @param {string} employees[].name - The name of an employee.
 * @param {string} employees[].department - The employee's department.
 */
```

**Comment by wehrstedt** [comment]
Solved with #15

**Comment by wehrstedt** [comment]
Forgot to add the test described above..

**Comment by tineheller** [comment]
Support and test for array parameters is added with #31
