### ISSUE TITLE
Support for generic types

### ISSUE THREAD

**Issue by whitlockjc** [otris/jsdoc-tsd#38]
Let's say I have a `function` that returns `Promise<*>`.  When that is converted to TSD, shouldn't that be `Promise.<any>` and not `Promise.<*>`?

**Comment by tineheller** [comment]
Actually I think it should be `Promise<any>` instead of `Promise.<*>` or `Promise.<any>`. I'm not sure for now why there is a dot... but we'll have a look at this.

**Comment by whitlockjc** [comment]
I see that `jsdoc2md/jsdoc-to-markdown` does it too: https://github.com/whitlockjc/json-refs/blob/master/docs/API.md  If you look at any of the parameterized types, you'll see a dot.  Not sure if it's intentional or not but I _think_ TypeScript doesn't need/want it.

**Comment by wehrstedt** [comment]
Fixed with https://github.com/otris/jsdoc-tsd/pull/46
