### ISSUE TITLE
Multi-dimensional array with different types

### ISSUE THREAD

**Issue by allejo** [otris/jsdoc-tsd#41]
Given I have the following jsdoc for a function,

```js
/**
 * @param {Array<Array<string|CustomObject>>} [field] ...
 */
function myFunction(field) {}
```

This is the resulting invalid TS that I get:

```ts
static myFunction(field?: Array.<(string|CustomObject)[]): void;
```

Is there a correct way of handling multi-dimensional arrays of different types or is this a bug in the generation?

**Comment by wehrstedt** [comment]
This is a bug in the current version, but the issue belongs to #39 and #38. I will try to fix it now.

**Comment by allejo** [comment]
Great! Thanks for the fix 👍
