### ISSUE TITLE
A 'declare' modifier cannot be used in an already ambient context

### ISSUE THREAD

**Issue by whitlockjc** [otris/jsdoc-tsd#49]
As reported in https://github.com/whitlockjc/json-refs/issues/140, it seems like a `declare` in a `module`, `namespace`, ... causes the error thrown in the title.  https://github.com/whitlockjc/json-refs/pull/143 shows how to fix this and has some details.

**Comment by wehrstedt** [comment]
Can you give me an example of the input, the output and what you expect it should look like?

**Comment by whitlockjc** [comment]
https://github.com/whitlockjc/json-refs is a perfect example.  `index.js` and `lib/typedefs.js` end up creating the TypeScript definitions in `index.d.ts`.  What happens is if you have a `@typedef {object}` that is a `@memberof module:json-refs`, when the `interface` is declared, it should not have a `declare` keyword.  So [declare interface JsonRefsOptions](https://github.com/whitlockjc/json-refs/blob/master/index.d.ts#L143), it should just be `interface JsonRefsOptions`.  _(Not sure if it should be `export interface JsonRefsOptions`, I'm new to TypeScript.

**Comment by wehrstedt** [comment]
Okay, I will have a look tomorrow

**Comment by wehrstedt** [comment]
Good news: It can be fixed by just upgrading [dts-dom](https://github.com/RyanCavanaugh/dts-dom)

**Comment by wehrstedt** [comment]
published `v1.0.4`. Can you verify it, please?

**Comment by whitlockjc** [comment]
`v1.0.4` fixes my issues.
