### ISSUE TITLE
Array of module types generated as `any[]`

### ISSUE THREAD

**Issue by whitlockjc** [otris/jsdoc-tsd#52]
Let's say I have a function that has a `@returns {module:sway~Operation[]}`, the generated TSD has `any[]`.  For example, [this JSDoc](https://github.com/apigee-127/sway/blob/master/lib/types/api.js#L162) is generated as [this TSD](https://github.com/apigee-127/sway/blob/master/index.d.ts#L232).  It should be `Operation[]` and not `any[]`.

**Comment by wehrstedt** [comment]
Modules are quite tricky to handle, I don't know when I have time to check this. If you like you can write a test for your case like [this one](https://github.com/otris/jsdoc-tsd/blob/master/test/module/test.parseModule.ts#L39) (should not be that hard) and debug the `parse`-function or the `prepareResults-function`. I assume that theres a problem with the function [mapVariableType](https://github.com/otris/jsdoc-tsd/blob/master/src/core/jsdoc-tsd-parser.ts#L680), should be pretty easy to debug
